services:
  - type: web
    name: fleet-api-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: TZ
        value: Europe/Moscow
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: fleet-api-server
          type: web
          property: url
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheck:
      path: /status
      interval: 30s
      timeout: 10s
      gracePeriod: 30s 